#!/bin/sh
#To be placed in /usr/local/etc/rc.d/icecast2. One per instance. Change the instance number 2 to whatever
#
# $FreeBSD: ports/audio/icecast2/files/icecast2.sh.in,v 1.8 2010/08/16 15:23:57 ohauer Exp $
#

# PROVIDE: icecast2
# REQUIRE: DAEMON
# BEFORE:  LOGIN
# KEYWORD: shutdown

# Add the following line to /etc/rc.conf to enable `icecast2'.
#
#icecast3_enable="YES"
#
# To specify a non-default configuration file, set icecast_config
# in /etc/rc.conf: 
#
#icecast3_config="/usr/local/etc/icecast3.xml"
#
# Make sure the <changeowner> section in your configuration file is
# not commented out - icecast refuses to run as root.
#

. /etc/rc.subr

name="icecast2"
rcvar=`set_rcvar`
pidfile=/usr/local/share/icecast/icecast2.pid

command="/usr/local/bin/icecast"
command_args="-b -c /usr/local/etc/icecast2.xml 1>/dev/null"
extra_commands="reload"

# read configuration and set defaults
load_rc_config "$name"
: ${icecast_enable="NO"}
: ${icecast_config="/usr/local/etc/${name}.xml"}
: ${icecast_flags="-c ${icecast_config}"}

required_files="${icecast_config}"

run_rc_command "$1"
